language: java
jdk: oraclejdk8
jobs:
  include:
  - stage: build
    script:
    - mvn clean install -B
  - stage: static code analysis
    addons:
      sonarcloud:
        organization: jstfhv-github
        token: $SONAR_TOKEN
    script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent javadoc:javadoc verify sonar:sonar
    - cd ..
    - "git clone https://github.com/jstfhv/CI_Docs.git"
    - rm -rf CI_Docs/jacoco-ut CI_Docs/apidocs
    - cp -r CI-WeatherApp/target/site/jacoco-ut CI_Docs/
    - cp -r CI-WeatherApp/target/site/apidocs CI_Docs/
    - cd CI_Docs
    - git add --all
    - git commit -am "update documentation"
    - git push "https://${TRAVIS_GITHUB_TOKEN}@github.com/jstfhv/CI_Docs.git" master
  - stage: deploy to heroku
    deploy:
      provider: heroku
      api_key: $HEROKU_API_KEY
      app: fhvweatherapp
      on:
        repo: jstfhv/CI-WeatherApp
  - stage: automatic user acceptance and performance tests on staging
    script:
    - cd ..
    - "git clone https://github.com/jstfhv/CI_Test_Weatherapp.git"
    - cd CI_Test_Weatherapp
    - mvn verify
    - cd ..
    - "git clone https://github.com/jstfhv/CI_Docs.git"
    - rm -rf CI_Docs/cukedoctor CI_Docs/walk_through.mp4
    - cp -r CI_Test_Weatherapp/target/cukedoctor CI_Docs/
    - rm -rf CI_Docs/jmeter
    - cp -r CI_Test_Weatherapp/target/jmeter/reports/performance* CI_Docs/jmeter
    - cd CI_Docs
    - ../CI_Test_Weatherapp/scripts/get_testingbot_video.py
    - git add --all
    - git commit -am "update tests"
    - git push "https://${TRAVIS_GITHUB_TOKEN}@github.com/jstfhv/CI_Docs.git" master
