language: java
jdk: oraclejdk8

jobs:
  include:
  - stage: build
    -script:
      - mvn deploy

  - stage: static code analysis
    addons:
      sonarcloud:
        organization: CI-WeatherApp
        token: $SONAR_TOKEN
    script:
      - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
