language: java
jdk: oraclejdk8

jobs:
  include:
  - stage: build
    -script:
      - ./mvnw clean install -B

  - stage: static code analysis
    addons:
      sonarcloud:
        organization: "jstfhv-github"
        token: $SONAR_TOKEN
    script:
      - ./mvnw org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
