language: java
jdk: oraclejdk8
jobs:
  include:
  - stage: build
    script:
    - mvn clean install -B
  - stage: static code analysis
    addons:
      sonarcloud:
        organization: jstfhv-github
        token: $SONAR_TOKEN
    script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
    - cd ..
    - "git clone https://github.com/jstfhv/CI_Docs.git"
    - rm -rf CI_Docs/generated/jacoco-ut CI_Docs/generated/jacoco-it CI_Docs/generated/apidocs
    - ls CI-WeatherApp/target
    - ls CI-WeatherApp/target/size
    - cp -r CI-WeatherApp/target/site/jacoco-ut CI_Docs/generated/
    - cp -r CI-WeatherApp/target/site/jacoco-it CI_Docs/generated/
    - cp -r CI-WeatherApp/target/site/apidocs CI_Docs/generated/
    - cd CI_Docs/generated
    - git add --all
    - git commit -am "update documentation"
    - git push "https://${TRAVIS_GITHUB_TOKEN}@github.com/jstfhv/CI_Docs.git" master
  - stage: deploy to heroku
    deploy:
      provider: heroku
      api_key: $HEROKU_API_KEY
      app: fhvweatherapp
      on:
        repo: jstfhv/CI-WeatherApp