language: java
jdk: oraclejdk8
jobs:
  include:
  - stage: build
    script:
    - mvn clean install -B
  - stage: static code analysis
    addons:
      sonarcloud:
        organization: jstfhv-github
        token: $SONAR_TOKEN
    script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - stage: deploy to heroku
      deploy:
        provider: heroku
          app: fhvweatherapp
          api_key: $HEROKU_TOKEN
  
